# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-17 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_registration', '0002_auto_20181115_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('is_daily', models.BooleanField()),
                ('is_weekly', models.BooleanField()),
                ('is_monthly', models.BooleanField()),
                ('is_longterm', models.BooleanField()),
                ('is_completed', models.BooleanField()),
                ('due_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='login_and_registration.User')),
            ],
        ),
    ]
