# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='is_daily',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='is_monthly',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='is_weekly',
        ),
        migrations.AddField(
            model_name='agreement',
            name='frequency_of_agreement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
