# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0002_auto_20181119_2013'),
        ('to_dos', '0002_auto_20181119_1249'),
    ]

    operations = [
    ]
