# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0003_merge_20181119_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='is_longterm',
            field=models.BooleanField(default=False),
        ),
    ]
